version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: memory-postgres
    restart: unless-stopped
    networks:
      - traefik_net
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432"  # Internal only
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  traefik_net:
    external: true