version: '3.8'

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - /srv/workspaces:/srv:rw
      - filebrowser_data:/database
      - ./config:/config
    environment:
      - FB_DATABASE=/database/filebrowser.db
      - FB_CONFIG=/config/settings.json
    user: "1000:1000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.millyweb.com`)"
      - "traefik.http.routers.filebrowser.entrypoints=websecure"
      - "traefik.http.routers.filebrowser.tls.certresolver=ledns"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

volumes:
  filebrowser_data:

networks:
  traefik_net:
    external: true