version: '3.8'

services:
  workbench:
    image: nginx:alpine
    container_name: workbench
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.workbench.rule=Host(`workbench.millyweb.com`)"
      - "traefik.http.routers.workbench.entrypoints=websecure"
      - "traefik.http.routers.workbench.tls.certresolver=ledns"
      - "traefik.http.services.workbench.loadbalancer.server.port=80"
      - "traefik.http.routers.workbench.middlewares=default-headers"

networks:
  traefik_net:
    external: true
