version: '3.8'

services:
  dev-hub:
    image: nginx:alpine
    container_name: dev-hub
    restart: unless-stopped
    networks:
      - traefik_net
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dev-hub.rule=Host(`dev.millyweb.com`)"
      - "traefik.http.routers.dev-hub.entrypoints=websecure"
      - "traefik.http.routers.dev-hub.tls.certresolver=ledns"
      - "traefik.http.services.dev-hub.loadbalancer.server.port=80"
      - "traefik.http.routers.dev-hub.middlewares=default-headers"

networks:
  traefik_net:
    external: true
